pre-commit:
  parallel: true
  commands:
    prettier:
      run: pnpm exec prettier --write {staged_files}
      glob: "*.{ts,tsx,js,cjs,mjs,md,mdx,json,yml,yaml}"
      stage_fixed: true
    eslint:
      run: pnpm exec eslint --fix {staged_files}
      glob: "*.{ts,tsx}"
      stage_fixed: true
    markdownlint:
      run: pnpm exec markdownlint-cli2 --fix -- {staged_files}
      glob: "*.{md,markdown}"
      stage_fixed: true

commit-msg:
  commands:
    commitlint:
      run: pnpm exec commitlint --edit {1}
